"""Create tables 'identical_photo'

Revision ID: 9294bb66b012
Revises: d5d2beb3359a
Create Date: 2024-04-04 02:18:34.455809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9294bb66b012"
down_revision: Union[str, None] = "d5d2beb3359a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identical_photo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("photo_left", sa.Integer(), nullable=False),
        sa.Column("photo_right", sa.Integer(), nullable=False),
        sa.Column("cos", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["photo_left"],
            ["photo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_right"],
            ["photo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("identical_photo")
    # ### end Alembic commands ###
