"""Fix photo table

Revision ID: d1f202ea1cb7
Revises: 9294bb66b012
Create Date: 2024-04-05 19:40:04.624220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1f202ea1cb7"
down_revision: Union[str, None] = "9294bb66b012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "identical_photo_photo_right_fkey",
        "identical_photo",
        type_="foreignkey",
    )
    op.drop_column("identical_photo", "cos")
    op.drop_constraint("photo_name_key", "photo", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("photo_name_key", "photo", ["name"])
    op.add_column(
        "identical_photo",
        sa.Column(
            "cos",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "identical_photo_photo_right_fkey",
        "identical_photo",
        "photo",
        ["photo_right"],
        ["id"],
    )
    # ### end Alembic commands ###
